version: '3.8'

services:
  db:
    image: postgres:15
    container_name: encurl-container
    environment:
      POSTGRES_DB: encurldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
